---
title: "Interactive analysis of DESeq analysis"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    code_folding: hide
params:
  path_deseq_rda: ""
  path_deseq_csv: ""
  top_regulated_genes_for_plotting: 10
  dev: TRUE
---

TODO Read rda

```{r setup}
library(magrittr)
library(crosstalk)
library(plotly)

rmarkdown_params <- list()
# Hack to be able to use infinite moon reader
if (params$dev == TRUE) {
  rmarkdown_params$path_deseq_rda <- "/beegfs/scratch/bruening_scratch/pklemm/2019-04-philipp-cers/nf-rnaseq/results/DESeq2/deseq2_diff.rds"
  rmarkdown_params$path_deseq_csv <- "/beegfs/scratch/bruening_scratch/pklemm/2019-04-philipp-cers/nf-rnaseq/results/DESeq2/deseq2_diff.csv"
  rmarkdown_params$top_regulated_genes_for_plotting <- params$top_regulated_genes_for_plotting
} else {
  rmarkdown_params$path_deseq_rda <- params$path_deseq_rda
  rmarkdown_params$path_deseq_csv <- params$path_deseq_csv
  rmarkdown_params$top_regulated_genes_for_plotting <- params$top_regulated_genes_for_plotting
}

```

```{r read_rda}

paste0(
  "Load DESeq2 rds file from ",
  rmarkdown_params$path_deseq_rda
)

deseq_result <- readRDS(rmarkdown_params$path_deseq_rda)
deseq_result_frame <- readr::read_csv(rmarkdown_params$path_deseq_csv)
```

This can probably be moved to a separate markdown file to keep the footprint of the DESeq part low.

```{r get_deseq_counts, cache = TRUE}

deseq_counts <- deseq_result %>%
  DESeq2::counts(
    normalized = TRUE,
    replaced = FALSE
  ) %>%
  as.data.frame() %>%
  tibble::rownames_to_column("ensembl_id") %>%
  # Attach adjusted p-value
  dplyr::left_join(
    .,
    deseq_result_frame %>%
      dplyr::select(row, padj),
    by = c("ensembl_id" = "row")
  ) %>%
  # Order by adjusted p-value
  dplyr::arrange(padj) %>%
  rmyknife::attach_biomart(
    ensembl_version = 97,
    ensembl_id_var = "ensembl_id",
    attributes = "external_gene_name",
  ) %>%
  dplyr::rename(name = external_gene_name) %>%
  tibble::as_tibble()

```

```{r plot_genes, warning = FALSE}

deseq_counts_top_n <- deseq_counts %>%
  # Keep top n genes for plotting
  head(rmarkdown_params$top_regulated_genes_for_plotting) %>%
  # Remove padj
  dplyr::select(-padj, -ensembl_id) %>%
  tidyr::pivot_longer(-name, "sample") %>%
  # Attach treatment
  dplyr::left_join(
    col_data,
    by = c("sample" = "id")
  )

sd <- SharedData$new(deseq_counts_top_n)
filter_select(
  id = "name",
  label = "Select Gene",
  sharedData = sd,
  group = ~name,
  multiple = FALSE
  # selected does not work properly at the moment. See https://github.com/rstudio/crosstalk/pull/70 for details
  # selected = deseq_counts_top_n %>% 
  #   head(1) %>%
  #   dplyr::select(gene) %>%
  #   dplyr::pull()
  )

plot <- sd %>% ggplot2::ggplot(
    ggplot2::aes(
      x = treatment,
      y = value
    )
  ) +
  ggplot2::geom_point() +
  ggplot2::geom_boxplot()

plotly::ggplotly(plot)

```

https://genviz.org/module-04-expression/0004/02/01/DifferentialExpression/